# RankUp Plugin made by esh123cookie 
# Discord: bigbozzlmao#4035
# Plugin made for people who cannot find an updated version for rankup
# To use this plugin you will need pureperms and purechat

# not enough money message
msg: "you do not have enough money to rankup"

# In Order
## rank = How the suffix or prefix would look after using the command rankup
## price = Prices for each rank
## cmd = Command
## permission = Permissions for each rank

# Use only for commands:
## tags $p, $money
## $p = player name
## $money = player money

# For Cmd put nothing if you want the command to do nothing

# Rank A
cmd:
cmd2:
permission1: "rankup.a.use"

# Rank B
cmd3:
cmd4:
permission2: "rankup.b.use"

# Rank C
cmd5:
cmd6:
permission1: "rankup.c.use"

# Rank D  
cmd7:
cmd8:
permission4: "rankup.d.use"

# Rank E
cmd9:
cmd10:
permission5: "rankup.e.use"

# Rank F
cmd11:
cmd12:
permission6: "rankup.f.use"

# Rank G
cmd13:
cmd14:
permission7: "rankup.g.use"

# Rank H
cmd15:
cmd16:
permission8: "rankup.h.use"

# Rank I
cmd17:
cmd18:
permission9: "rankup.i.use"

# Rank J
cmd19:
cmd20:
permission10: "rankup.j.use"

# Rank K
cmd21:
cmd22:
permission11: "rankup.k.use"

# Rank L
cmd23:
cmd24:
permission12: "rankup.l.use"

# Rank M
cmd25:
cmd26:
permission13: "rankup.m.use"

# Rank N
cmd27:
cmd28:
permission14: "rankup.a.use"

# Rank O
cmd29:
cmd30:
permission15: "rankup.o.use"

# Rank P
cmd31:
cmd32:
permission16: "rankup.p.use"

# Rank Q
cmd33:
cmd34:
permission17: "rankup.q.use"

# Rank R
cmd35:
cmd36:
permission18: "rankup.r.use"

# Rank S
cmd37:
cmd38:
permission19: "rankup.s.use"

# Rank T
cmd39:
cmd40:
permission20: "rankup.t.use"

# Rank U
cmd41:
cmd42:
permission21: "rankup.u.use"

# Rank V
cmd43:
cmd44:
permission22: "rankup.v.use"

# Rank W
cmd45:
cmd46:
permission23: "rankup.w.use"

# Rank X
cmd47:
cmd48:
permission24: "rankup.x.use"

# Rank Y
cmd49:
cmd50:
permission25: "rankup.y.use"

# Rank Z
cmd51:
cmd52:
permission26: "rankup.z.use"

# version 1.0.0
# Simple rankup plugin 
